export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';  
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';  
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';  
export const NOTE_POST_SUCCESS = 'NOTE_POST_SUCCESS';  
